/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perhotelan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class a_Edit_Kamar extends javax.swing.JFrame {

    /**
     * Creates new form a_Edit_Kamar
     */
    Connection con = new dbConnect().databaseConnect();
    
    public a_Edit_Kamar() {
        initComponents();
        kodeKamar_Search();
    }
    public void kodeKamar_Search(){
        String sqlSearchKodeKamar = "SELECT * FROM tbl_kamar";
        try {
            PreparedStatement pstKode_Kamar = con.prepareStatement(sqlSearchKodeKamar);
            ResultSet rsKodeView = pstKode_Kamar.executeQuery(sqlSearchKodeKamar);
            while (rsKodeView.next()) {
                sc_Kode_Kamar.addItem(rsKodeView.getString("kode_Kamar"));
            }
        } catch (Exception e) {
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sc_Kode_Kamar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scv_No_Kamar = new javax.swing.JTextField();
        scv_Tipe_Kamar = new javax.swing.JTextField();
        scv_Lantai_Kamar = new javax.swing.JTextField();
        scv_Harga_Peminjaman = new javax.swing.JTextField();
        kodeKamar_Search = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        af_Inp_NoKamar = new javax.swing.JTextField();
        af_inp_HargaPeminjaman = new javax.swing.JTextField();
        af_Inp_TipeKamar = new javax.swing.JComboBox<>();
        af_Inp_LantaiKamar = new javax.swing.JComboBox<>();
        btn_Update_No = new javax.swing.JButton();
        btn_Update_Tipe = new javax.swing.JButton();
        btn_Update_Lantai = new javax.swing.JButton();
        btn_Update_Harga = new javax.swing.JButton();
        btn_ExitEditKamar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Kamar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Kamar");

        sc_Kode_Kamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sc_Kode_Kamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Kode Kamar---" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No Kamar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipe Kamar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lantai Kamar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga Peminjaman");

        scv_No_Kamar.setEditable(false);

        scv_Tipe_Kamar.setEditable(false);

        scv_Lantai_Kamar.setEditable(false);

        scv_Harga_Peminjaman.setEditable(false);

        kodeKamar_Search.setBackground(new java.awt.Color(51, 255, 51));
        kodeKamar_Search.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        kodeKamar_Search.setText("Cari");
        kodeKamar_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeKamar_SearchActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("=>");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("=>");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("=>");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("=>");

        af_Inp_TipeKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Bisnis", "VIP" }));

        af_Inp_LantaiKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lantai 1", "Lantai 2", "Lantai 3", "Lantai 4", "Lantai 5" }));

        btn_Update_No.setText("Update");
        btn_Update_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_NoActionPerformed(evt);
            }
        });

        btn_Update_Tipe.setText("Update");
        btn_Update_Tipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_TipeActionPerformed(evt);
            }
        });

        btn_Update_Lantai.setText("Update");
        btn_Update_Lantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_LantaiActionPerformed(evt);
            }
        });

        btn_Update_Harga.setText("Update");
        btn_Update_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_HargaActionPerformed(evt);
            }
        });

        btn_ExitEditKamar.setBackground(new java.awt.Color(255, 51, 51));
        btn_ExitEditKamar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_ExitEditKamar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ExitEditKamar.setText("Keluar");
        btn_ExitEditKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitEditKamarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(66, 66, 66)
                                .addComponent(scv_No_Kamar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)
                                .addComponent(scv_Tipe_Kamar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(44, 44, 44)
                                .addComponent(scv_Lantai_Kamar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scv_Harga_Peminjaman))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sc_Kode_Kamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addComponent(kodeKamar_Search)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(af_Inp_NoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(af_Inp_TipeKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(af_inp_HargaPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(af_Inp_LantaiKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Update_No, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(btn_Update_Tipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Update_Lantai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Update_Harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btn_ExitEditKamar)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sc_Kode_Kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeKamar_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(scv_No_Kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(af_Inp_NoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update_No, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(scv_Tipe_Kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(af_Inp_TipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update_Tipe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(scv_Lantai_Kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(af_Inp_LantaiKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update_Lantai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(scv_Harga_Peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(af_inp_HargaPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ExitEditKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kodeKamar_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeKamar_SearchActionPerformed
        // TODO add your handling code here:
        String queryView_KodeKamar = "SELECT * FROM tbl_kamar WHERE kode_Kamar='"+ sc_Kode_Kamar.getSelectedItem() +"'";
        try {
            PreparedStatement pst_ViewSearch = con.prepareStatement(queryView_KodeKamar);
            ResultSet rs_ViewSearch = pst_ViewSearch.executeQuery();
            if (rs_ViewSearch.next()) {
                scv_No_Kamar.setText(rs_ViewSearch.getString("no_Kamar"));
                scv_Tipe_Kamar.setText(rs_ViewSearch.getString("tipe_Kamar"));
                scv_Lantai_Kamar.setText(rs_ViewSearch.getString("lantai_Kamar"));
                scv_Harga_Peminjaman.setText(rs_ViewSearch.getString("hargaSewa_Kamar"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e,"Gagal Mendapat Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_kodeKamar_SearchActionPerformed

    private void btn_Update_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_NoActionPerformed
        // TODO add your handling code here:
        String updateNo_Kamar = "UPDATE tbl_kamar SET no_Kamar='"+af_Inp_NoKamar.getText()+"' WHERE kode_Kamar='"+ (String)sc_Kode_Kamar.getSelectedItem() +"'";
        try {
            
            PreparedStatement pst_UpdateNo = con.prepareStatement(updateNo_Kamar);
            pst_UpdateNo.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Update data Nomor Kamar Berhasil","Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Update data Nomor Kamar Gagal","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_Update_NoActionPerformed

    private void btn_Update_TipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_TipeActionPerformed
        // TODO add your handling code here:
        String updateTipe_Kamar = "UPDATE tbl_kamar SET tipe_Kamar='"+ (String)af_Inp_TipeKamar.getSelectedItem() +"' WHERE kode_Kamar='"+ (String)sc_Kode_Kamar.getSelectedItem() +"'";
        try {
            
            PreparedStatement pst_UpdateTipe = con.prepareStatement(updateTipe_Kamar);
            pst_UpdateTipe.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Update data Tipe Kamar Berhasil","Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Update data Tipe Kamar Gagal","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_Update_TipeActionPerformed

    private void btn_Update_LantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_LantaiActionPerformed
        // TODO add your handling code here:
        String updateLantai_Kamar = "UPDATE tbl_kamar SET lantai_Kamar='"+ (String)af_Inp_LantaiKamar.getSelectedItem() +"' WHERE kode_Kamar='"+ (String)sc_Kode_Kamar.getSelectedItem() +"'";
        
        try {
            PreparedStatement pst_UpdateLantai = con.prepareStatement(updateLantai_Kamar);
            pst_UpdateLantai.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Update data Lantai Kamar Berhasil","Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Update data Lantai Kamar Gagal","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_Update_LantaiActionPerformed

    private void btn_Update_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_HargaActionPerformed
        // TODO add your handling code here:
        String updateHarga_Kamar = "UPDATE tbl_kamar SET hargaSewa_Kamar='"+af_inp_HargaPeminjaman.getText()+"' WHERE kode_Kamar='"+ (String)sc_Kode_Kamar.getSelectedItem() +"'";
        try {
            
            PreparedStatement pst_UpdateHarga = con.prepareStatement(updateHarga_Kamar);
            pst_UpdateHarga.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Update data Harga Sewa Kamar Berhasil","Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Update data Harga Sewa Kamar Gagal","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_Update_HargaActionPerformed

    private void btn_ExitEditKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitEditKamarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_ExitEditKamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a_Edit_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a_Edit_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a_Edit_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a_Edit_Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a_Edit_Kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> af_Inp_LantaiKamar;
    private javax.swing.JTextField af_Inp_NoKamar;
    private javax.swing.JComboBox<String> af_Inp_TipeKamar;
    private javax.swing.JTextField af_inp_HargaPeminjaman;
    private javax.swing.JButton btn_ExitEditKamar;
    private javax.swing.JButton btn_Update_Harga;
    private javax.swing.JButton btn_Update_Lantai;
    private javax.swing.JButton btn_Update_No;
    private javax.swing.JButton btn_Update_Tipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kodeKamar_Search;
    private javax.swing.JComboBox<String> sc_Kode_Kamar;
    private javax.swing.JTextField scv_Harga_Peminjaman;
    private javax.swing.JTextField scv_Lantai_Kamar;
    private javax.swing.JTextField scv_No_Kamar;
    private javax.swing.JTextField scv_Tipe_Kamar;
    // End of variables declaration//GEN-END:variables
}
