/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perhotelan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class a_PageKamar extends javax.swing.JFrame {

    Connection con = new dbConnect().databaseConnect();
    
    public a_PageKamar() {
        initComponents();
        
        tampil_Kamar();
        tampil_Karyawan();
        tampil_HistoryLog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbl_History = new javax.swing.JTabbedPane();
        panel_Kamar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_TambahKamar = new javax.swing.JButton();
        btn_EditKamar = new javax.swing.JButton();
        btn_HapusKamar = new javax.swing.JButton();
        btn_RefreshKamar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Kamar = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        panel_Pegawai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Karyawan = new javax.swing.JTable();
        btn_RefreshKaryawan = new javax.swing.JButton();
        btn_TambahKaryawan = new javax.swing.JButton();
        btn_EditKaryawan = new javax.swing.JButton();
        btn_HapusKaryawan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_Riwayat = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_HistoryAccess = new javax.swing.JTable();
        btn_refresh_History = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        tbl_History.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        btn_TambahKamar.setText("Tambah");
        btn_TambahKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahKamarActionPerformed(evt);
            }
        });

        btn_EditKamar.setText("Edit");
        btn_EditKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditKamarActionPerformed(evt);
            }
        });

        btn_HapusKamar.setText("Hapus");
        btn_HapusKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusKamarActionPerformed(evt);
            }
        });

        btn_RefreshKamar.setText("Refresh");
        btn_RefreshKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshKamarActionPerformed(evt);
            }
        });

        tbl_Kamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_Kamar);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Halaman Data Kamar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TambahKamar)
                    .addComponent(btn_RefreshKamar)
                    .addComponent(btn_EditKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HapusKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_RefreshKamar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TambahKamar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_EditKamar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_HapusKamar)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_KamarLayout = new javax.swing.GroupLayout(panel_Kamar);
        panel_Kamar.setLayout(panel_KamarLayout);
        panel_KamarLayout.setHorizontalGroup(
            panel_KamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_KamarLayout.setVerticalGroup(
            panel_KamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KamarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbl_History.addTab("Kamar", panel_Kamar);

        panel_Pegawai.setBackground(new java.awt.Color(102, 102, 255));

        tbl_Karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Karyawan);

        btn_RefreshKaryawan.setText("Refresh");
        btn_RefreshKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshKaryawanActionPerformed(evt);
            }
        });

        btn_TambahKaryawan.setText("Tambah");
        btn_TambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahKaryawanActionPerformed(evt);
            }
        });

        btn_EditKaryawan.setText("Edit");
        btn_EditKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditKaryawanActionPerformed(evt);
            }
        });

        btn_HapusKaryawan.setText("Hapus");
        btn_HapusKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusKaryawanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Halaman Data Pegawai");

        javax.swing.GroupLayout panel_PegawaiLayout = new javax.swing.GroupLayout(panel_Pegawai);
        panel_Pegawai.setLayout(panel_PegawaiLayout);
        panel_PegawaiLayout.setHorizontalGroup(
            panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PegawaiLayout.createSequentialGroup()
                .addGroup(panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_PegawaiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_PegawaiLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TambahKaryawan)
                    .addComponent(btn_RefreshKaryawan)
                    .addComponent(btn_EditKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HapusKaryawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_PegawaiLayout.setVerticalGroup(
            panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_PegawaiLayout.createSequentialGroup()
                        .addComponent(btn_RefreshKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TambahKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_EditKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_HapusKaryawan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tbl_History.addTab("Pegawai", panel_Pegawai);

        panel_Riwayat.setBackground(new java.awt.Color(102, 102, 255));

        tbl_HistoryAccess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_HistoryAccess);

        btn_refresh_History.setText("Refresh");
        btn_refresh_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_HistoryActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Halaman Data Riwayat Pengguna Applikasi");

        javax.swing.GroupLayout panel_RiwayatLayout = new javax.swing.GroupLayout(panel_Riwayat);
        panel_Riwayat.setLayout(panel_RiwayatLayout);
        panel_RiwayatLayout.setHorizontalGroup(
            panel_RiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(panel_RiwayatLayout.createSequentialGroup()
                .addGroup(panel_RiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_RiwayatLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(btn_refresh_History, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_RiwayatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        panel_RiwayatLayout.setVerticalGroup(
            panel_RiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_RiwayatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_refresh_History, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbl_History.addTab("Riwayat Penguna Aplikasi", panel_Riwayat);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Applikasi Perhotel Bagian Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl_History)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(tbl_History, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_History.getAccessibleContext().setAccessibleName("Kamar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RefreshKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshKaryawanActionPerformed
        // TODO add your handling code here:
        tampil_Karyawan();
    }//GEN-LAST:event_btn_RefreshKaryawanActionPerformed

    private void btn_EditKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditKaryawanActionPerformed
        // TODO add your handling code here:
        a_Edit_Karyawan popEdit_Karyawan = new a_Edit_Karyawan();
        popEdit_Karyawan.show();
    }//GEN-LAST:event_btn_EditKaryawanActionPerformed

    private void btn_TambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahKaryawanActionPerformed
        // TODO add your handling code here:
        a_Tambah_Karyawan popTambah_Karyawan = new a_Tambah_Karyawan();
        popTambah_Karyawan.show();
    }//GEN-LAST:event_btn_TambahKaryawanActionPerformed

    private void btn_HapusKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusKaryawanActionPerformed
        // TODO add your handling code here:
        a_Delete_Karyawan popDelete_Karyawan = new a_Delete_Karyawan();
        popDelete_Karyawan.show();
    }//GEN-LAST:event_btn_HapusKaryawanActionPerformed

    private void btn_refresh_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_HistoryActionPerformed
        // TODO add your handling code here:
        tampil_HistoryLog();
    }//GEN-LAST:event_btn_refresh_HistoryActionPerformed

    private void btn_RefreshKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshKamarActionPerformed
        tampil_Kamar();
    }//GEN-LAST:event_btn_RefreshKamarActionPerformed

    private void btn_HapusKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusKamarActionPerformed
        // TODO add your handling code here:
        a_Delete_Kamar popDeleteKamar = new a_Delete_Kamar();
        popDeleteKamar.show();
    }//GEN-LAST:event_btn_HapusKamarActionPerformed

    private void btn_EditKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditKamarActionPerformed
        // TODO add your handling code here:
        a_Edit_Kamar popEditKamar = new a_Edit_Kamar();
        popEditKamar.show();
    }//GEN-LAST:event_btn_EditKamarActionPerformed

    private void btn_TambahKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahKamarActionPerformed
        // TODO add your handling code here:
        a_Tambah_Kamar popTambahKamar = new a_Tambah_Kamar();
        popTambahKamar.show();
    }//GEN-LAST:event_btn_TambahKamarActionPerformed

    private DefaultTableModel tabmode;
    
    public void tampil_Kamar(){
    
        Object []baris_Kamar = {"Kode Kamar", "No Kamar", "Tipe Kamar", "Lantai Kamar", "Harga Kamar Permalam"};
        tabmode = new DefaultTableModel(null, baris_Kamar);
        tbl_Kamar.setModel(tabmode);
        try {
            String sql = "SELECT * FROM tbl_kamar order by no_Kamar asc";
            Statement stat_kamar = con.createStatement();
            ResultSet kamarView = stat_kamar.executeQuery(sql);
            while (kamarView.next()) {
                String kode_Kamar = kamarView.getString("kode_Kamar");
                String no_Kamar = kamarView.getString("no_Kamar");
                String tipe_Kamar = kamarView.getString("tipe_Kamar");
                String lantai_Kamar = kamarView.getString("lantai_Kamar");
                String hargaSewa_Kamar = kamarView.getString("hargaSewa_Kamar");
                
                String[] dataKamar = {kode_Kamar, no_Kamar, tipe_Kamar, lantai_Kamar, hargaSewa_Kamar};
                tabmode.addRow(dataKamar);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //Bagian Krayawan
    
    public void tampil_Karyawan(){
        
        Object []baris_Karyawan = {"ID User", "Nama User", "Gender User", "Telp User", "Role User", "Pass User"};
        tabmode = new DefaultTableModel(null, baris_Karyawan);
        tbl_Karyawan.setModel(tabmode);
        try {
            String sql = "SELECT * FROM tbl_user order by user_Id asc";
            Statement stat_karyawan = con.createStatement();
            ResultSet karyawanView = stat_karyawan.executeQuery(sql);
            while (karyawanView.next()) {                
                String user_Id = karyawanView.getString("user_Id");
                String user_Nama = karyawanView.getString("user_Nama");
                String user_Gender = karyawanView.getString("user_Gender");
                String user_Tlp = karyawanView.getString("user_Tlp");
                String user_Role = karyawanView.getString("user_Role");
                String user_Password = karyawanView.getString("user_Password");
                
                String[] dataKaryawan = {user_Id, user_Nama, user_Gender, user_Tlp, user_Role, user_Password};
                tabmode.addRow(dataKaryawan);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void tampil_HistoryLog(){
        Object []baris_LogActivity = {"No Log", "Tanggal Access", "Nama Access", "Keterangan Access"};
        tabmode = new DefaultTableModel(null, baris_LogActivity);
        tbl_HistoryAccess.setModel(tabmode);
        String sql = "SELECT * FROM tbl_logactivity order by log_NoAccess";
        try {
            Statement stat_HistoryLog = con.createStatement();
            ResultSet rs_view_HistoryLog = stat_HistoryLog.executeQuery(sql);
            while (rs_view_HistoryLog.next()) {
                String log_NoAccess = rs_view_HistoryLog.getString("log_NoAccess");
                String log_TglAccess = rs_view_HistoryLog.getString("log_TglAccess");
                String log_UserName = rs_view_HistoryLog.getString("log_UserName");
                String log_KeteranganAcess = rs_view_HistoryLog.getString("log_KeteranganAccess");
                
                String[] dataLogHistory = {log_NoAccess, log_TglAccess,log_UserName, log_KeteranganAcess};
                tabmode.addRow(dataLogHistory);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a_PageKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EditKamar;
    private javax.swing.JButton btn_EditKaryawan;
    private javax.swing.JButton btn_HapusKamar;
    private javax.swing.JButton btn_HapusKaryawan;
    private javax.swing.JButton btn_RefreshKamar;
    private javax.swing.JButton btn_RefreshKaryawan;
    private javax.swing.JButton btn_TambahKamar;
    private javax.swing.JButton btn_TambahKaryawan;
    private javax.swing.JButton btn_refresh_History;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_Kamar;
    private javax.swing.JPanel panel_Pegawai;
    private javax.swing.JPanel panel_Riwayat;
    private javax.swing.JTabbedPane tbl_History;
    private javax.swing.JTable tbl_HistoryAccess;
    private javax.swing.JTable tbl_Kamar;
    private javax.swing.JTable tbl_Karyawan;
    // End of variables declaration//GEN-END:variables
}
