/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perhotelan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class a_PageKamar extends javax.swing.JFrame {

    Connection con = new dbConnect().databaseConnect();
    
    public a_PageKamar() {
        initComponents();
        
        tampil_Kamar();
        tampil_Karyawan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_Kamar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_TambahKamar = new javax.swing.JButton();
        btn_EditKamar = new javax.swing.JButton();
        btn_HapusKamar = new javax.swing.JButton();
        btn_RefreshKamar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Kamar = new javax.swing.JTable();
        panel_Pegawai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Karyawan = new javax.swing.JTable();
        btn_RefreshKaryawan = new javax.swing.JButton();
        btn_TambahKaryawan = new javax.swing.JButton();
        btn_EditKaryawan = new javax.swing.JButton();
        btn_HapusKaryawan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_TambahKamar.setText("Tambah");

        btn_EditKamar.setText("Edit");

        btn_HapusKamar.setText("Hapus");

        btn_RefreshKamar.setText("Refresh");
        btn_RefreshKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshKamarActionPerformed(evt);
            }
        });

        tbl_Kamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_Kamar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TambahKamar)
                    .addComponent(btn_RefreshKamar)
                    .addComponent(btn_EditKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HapusKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_RefreshKamar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TambahKamar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_EditKamar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_HapusKamar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_KamarLayout = new javax.swing.GroupLayout(panel_Kamar);
        panel_Kamar.setLayout(panel_KamarLayout);
        panel_KamarLayout.setHorizontalGroup(
            panel_KamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_KamarLayout.setVerticalGroup(
            panel_KamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KamarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kamar", panel_Kamar);

        tbl_Karyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Karyawan);

        btn_RefreshKaryawan.setText("Refresh");
        btn_RefreshKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshKaryawanActionPerformed(evt);
            }
        });

        btn_TambahKaryawan.setText("Tambah");

        btn_EditKaryawan.setText("Edit");

        btn_HapusKaryawan.setText("Hapus");

        javax.swing.GroupLayout panel_PegawaiLayout = new javax.swing.GroupLayout(panel_Pegawai);
        panel_Pegawai.setLayout(panel_PegawaiLayout);
        panel_PegawaiLayout.setHorizontalGroup(
            panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PegawaiLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TambahKaryawan)
                    .addComponent(btn_RefreshKaryawan)
                    .addComponent(btn_EditKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_HapusKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panel_PegawaiLayout.setVerticalGroup(
            panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_PegawaiLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(panel_PegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_PegawaiLayout.createSequentialGroup()
                        .addComponent(btn_RefreshKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TambahKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_EditKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_HapusKaryawan))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Pegawai", panel_Pegawai);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Riwayat Peminjam", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Kamar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RefreshKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshKamarActionPerformed
        tampil_Kamar();
    }//GEN-LAST:event_btn_RefreshKamarActionPerformed

    private void btn_RefreshKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RefreshKaryawanActionPerformed

    private DefaultTableModel tabmode;
    
    public void tampil_Kamar(){
    
        Object []baris_Kamar = {"Kode Kamar", "No Kamar", "Tipe Kamar", "Lantai Kamar", "Harga Kamar Permalam"};
        tabmode = new DefaultTableModel(null, baris_Kamar);
        tbl_Kamar.setModel(tabmode);
        try {
            String sql = "SELECT * FROM tbl_kamar order by no_Kamar asc";
            Statement stat_kamar = con.createStatement();
            ResultSet kamarView = stat_kamar.executeQuery(sql);
            while (kamarView.next()) {
                String kode_Kamar = kamarView.getString("kode_Kamar");
                String no_Kamar = kamarView.getString("no_Kamar");
                String tipe_Kamar = kamarView.getString("tipe_Kamar");
                String lantai_Kamar = kamarView.getString("lantai_Kamar");
                String hargaSewa_Kamar = kamarView.getString("hargaSewa_Kamar");
                
                String[] dataKamar = {kode_Kamar, no_Kamar, tipe_Kamar, lantai_Kamar, hargaSewa_Kamar};
                tabmode.addRow(dataKamar);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    //Bagian Krayawan
    
    public void tampil_Karyawan(){
        
        Object []baris_Karyawan = {"ID User", "Nama User", "Gender User", "Telp User", "Role User", "Pass User"};
        tabmode = new DefaultTableModel(null, baris_Karyawan);
        tbl_Karyawan.setModel(tabmode);
        try {
            String sql = "SELECT * FROM tbl_user order by user_Id asc";
            Statement stat_karyawan = con.createStatement();
            ResultSet karyawanView = stat_karyawan.executeQuery(sql);
            while (karyawanView.next()) {                
                String user_Id = karyawanView.getString("user_Id");
                String user_Nama = karyawanView.getString("user_Nama");
                String user_Gender = karyawanView.getString("user_Gender");
                String user_Tlp = karyawanView.getString("user_Tlp");
                String user_Role = karyawanView.getString("user_Role");
                String user_Password = karyawanView.getString("user_Password");
                
                String[] dataKaryawan = {user_Id, user_Nama, user_Gender, user_Tlp, user_Role, user_Password};
                tabmode.addRow(dataKaryawan);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(a_PageKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new a_PageKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EditKamar;
    private javax.swing.JButton btn_EditKaryawan;
    private javax.swing.JButton btn_HapusKamar;
    private javax.swing.JButton btn_HapusKaryawan;
    private javax.swing.JButton btn_RefreshKamar;
    private javax.swing.JButton btn_RefreshKaryawan;
    private javax.swing.JButton btn_TambahKamar;
    private javax.swing.JButton btn_TambahKaryawan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel_Kamar;
    private javax.swing.JPanel panel_Pegawai;
    private javax.swing.JTable tbl_Kamar;
    private javax.swing.JTable tbl_Karyawan;
    // End of variables declaration//GEN-END:variables
}
